// build-data.mjs — bake a host's supervibe artifact texts into board-data.js
// so the board opens with zero interaction (file:// pages cannot read local
// paths without a user gesture; baked data is the only gesture-free channel).
// Zero deps, Node >= 20. Usage:
//   node build-data.mjs <docs/superpowers> [out board-data.js]
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const [, , dirArg, outArg] = process.argv;
if (!dirArg) {
  console.error('usage: node build-data.mjs <docs/superpowers> [out board-data.js]');
  process.exit(2);
}
const root = resolve(dirArg);
if (!existsSync(root)) {
  console.error('not found: ' + root);
  process.exit(2);
}
const read = (sub) => existsSync(join(root, sub))
  ? readdirSync(join(root, sub))
      .filter((f) => f.endsWith('.md'))
      .map((f) => ({ name: sub + '/' + f, text: readFileSync(join(root, sub, f), 'utf8') }))
  : [];
const data = { folderName: 'docs/superpowers', roadmaps: read('roadmaps'), sprints: read('sprints') };
const out = resolve(outArg || 'board-data.js');
writeFileSync(out, '// generated by supervibe build-data.mjs — do not edit\nvar BOARD_DATA = ' + JSON.stringify(data) + ';\n');
console.log(out + ' — ' + data.roadmaps.length + ' epic doc(s), ' + data.sprints.length + ' sprint doc(s)');
